name: auth_repository
description: A package which controls Firebase Authentication.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  flutter:
    sdk: flutter
  google_sign_in: ^6.1.0

dev_dependencies:
  firebase_auth_platform_interface: ^6.15.0
  firebase_core_platform_interface: ^4.8.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  plugin_platform_interface: ^2.1.4
