name: user_repository
description: A package which controls User related operations.
publish_to: "none"
version: 1.0.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.8.5
  firebase_auth: ^4.7.3
  firebase_storage: ^11.2.6
  path_provider: ^2.1.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
